#include <stdlib.h>
#include <stdio.h>
#include <pthread.h>
#include <cpuid.h>

#define BUFFER_SIZE 32
#define TRUE 1
#define FALSE 0

struct bufferItem
{
	int randNum;	// generated by rdrand or Mersenne Twister depending on processor
	int waitTime;	// also random, should be between 2 and 9 seconds
};

struct bufferItem itemList[BUFFER_SIZE];	// global item list, shared between producer/consumer

int supportsRdRand; // global x86 support check

int getRandNum(int lowBoundary, int highBoundary) {
	if(supportsX86 == FALSE) {
		// use Mersenne Twister
	} else {
		// use rdrand
	}
}

void producer() {
	// produce random values for randNum, waitTime, and producerDelayTime

	// wait for producerDelayTime

	// add randNum/waitTime to item list, iff buffer is not full (if full, wait again)

	// lock thread access and write 

	// if successful, unlock

}

void consumer() {
	// check for emptiness of buffer - if empty, wait;

	// if not empty, lock thread access and read

	// print consumed information and unlock
}

int isX86(){
	const unsigned int flag_RDRAND = (1 << 30);
	unsigned int eax, ebx, ecx, edx;
	__get_cpuid(1, &eax, &ebx, &ecx, &edx);
	return ((ecx & flag_RDRAND) == flag_RDRAND);
}

int main(int argc, char* argv[]) {
	// check rdrand support
	supportsRdRand = isX86();


	// initialize concurrency/synchronization



	return 0;
}